config/routes.rb
Rails.application.routes.draw do
 
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  post 'likes/:micropost_id/create', to: 'likes#create'
  delete 'likes/:micropost_id/destroy', to: 'likes#destroy'
  resources :likes, only: [:show]
  resources :comments,          only: [:create, :destroy]
  resources :searchs,           only: [:index]
  resources :maps,              only: [:index]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
        if logged_in?
         @micropost  = current_user.microposts.build
         @feed_items = current_user.feed.paginate(page: params[:page])
        end
    end

    def help
        
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
 <h1>Help</h1>
 <p>This will be a help page for users.</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>釣果を共有しよう</h1>
　<p>Gyotakerをはじめよう</p>
  <div>
  <%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-primary w-75" %>
  </div>
  <div>
  <%= link_to "ログイン", login_path, class: "btn btn-lg btn-success mt-3 w-75 " %>
  </div>
</div>
<% end %>