config/routes.rb
Rails.application.routes.draw do
 
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  post 'likes/:micropost_id/create', to: 'likes#create'
  delete 'likes/:micropost_id/destroy', to: 'likes#destroy'
  resources :likes, only: [:show]
  resources :comments,          only: [:create, :destroy]
  resources :searchs,           only: [:index]
  resources :maps,              only: [:index]
end

app/views/shared/_comment_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "add a comments..." %>
  </div>
  <%= hidden_field_tag :micropost_id, @micropost.id%>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="image">
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <div class="current_location">
   <%=button_tag "現在位置を追加", type: "button", class: "mb-3", onclick: "getLocation()"%>
   <span id="address" class="address"></span>
   <%= f.hidden_field :latitude , value: nil%>
   <%= f.hidden_field :longitude , value: nil%>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

<script>
function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(setPosition);
    
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function setPosition(position) {
  var lat = position.coords.latitude;
  var lng = position.coords.longitude;

  var geocoder = new google.maps.Geocoder();
  var latlng = new google.maps.LatLng(lat, lng);
  geocoder.geocode({'latLng': latlng}, function(results, status) {
  
  if (status == google.maps.GeocoderStatus.OK) {
    var address_components = results[0].address_components;
    var components={}; 
    jQuery.each(address_components, function(k,v1) {jQuery.each(v1.types, function(k2, v2){components[v2]=v1.long_name});});
    document.getElementById('address').innerHTML =  retName(components.administrative_area_level_1) 
                                                  + retName(components.locality)
                                                  + retName(components.sublocality_level_1)
                                                  + retName(components.sublocality_level_2)
    document.getElementById('micropost_latitude').value = lat;
    document.getElementById('micropost_longitude').value = lng;
  }
  else {
    document.getElementById('address').innerHTML = "error";
  alert("エラー" + status);
  }
 });
}

function retName(argName){
  return retVal = (argName == null) ? "" : argName;
} 
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>