config/routes.rb
Rails.application.routes.draw do
 
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]

  post 'likes/:micropost_id/create', to: 'likes#create'
  delete 'likes/:micropost_id/destroy', to: 'likes#destroy'
  resources :likes, only: [:show]
  resources :comments,          only: [:create, :destroy]
  resources :searchs,           only: [:index]
  resources :maps,              only: [:index]
end

app/views/layouts/_footer.html.erb
<footer class="d-md-none">
<% if logged_in? %>
 <nav class="navbar navbar-expand navbar-dark bg-primary navbar-fixed-bottom">
  <div class="container">
   <ul class="navbar-nav f-outer">
    <li class="nav-item f-inner">
      <%= link_to maps_path do %>
       <span class="nav-link fas fa-globe-asia f-icon-size"></span>
      <% end %>
    </li>
     <li class="nav-item f-inner">
      <%= link_to searchs_path do %>
       <span class="nav-link fas fa-search f-icon-size"></span>
      <% end %>
    </li>
    <li class="nav-item f-inner">
     <%= link_to root_path do %>
       <span class="nav-link fas fa-plus-circle f-icon-size"></span>
      <% end %>
    </li>
    <li class="nav-item f-inner">
     <%= link_to like_path(current_user) do %>
      <span class="nav-link fas fa-heart f-icon-size"></span>
     <% end %>
    </li>
    <li class="nav-item f-inner">
      <%= link_to user_path(current_user) do %>
       <span class="nav-link fas fa-user f-icon-size"></span>
      <% end %>
    </li>
   </ul>
  </div>
 </nav>
 <%end%>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-fixed-top">
  <%= link_to "gyotaker", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home",   root_path , class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Help",   help_path , class: "nav-link" %>
      </li>
      <% if logged_in? %>
       <li class="nav-item active">
        <%= link_to "Users", users_path , class: "nav-link" %>
       </li>
       <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", current_user , class: "dropdown-item" %>
          <%= link_to "Settings", edit_user_path(current_user) , class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", logout_path, class: "dropdown-item", method: :delete %>
        </div>
       </li>
      <% else %>
       <li><%= link_to "Log in", login_path , class: "nav-link active" %></li>
      <% end %>
    </ul>
    
    <% if logged_in? %>
     <%= search_form_for @search, class: "form-inline my-2 mt-lg-3 navbar-right d-none d-md-inline", url: users_path do |f| %>
      <%= f.text_field :name_cont, class: "form-control mr-sm-2", placeholder: 'User search...' %>
      <%= f.submit ("Search") , class: 'btn btn-light my-2 my-sm-0 mr-md-5'%>
     <% end %>
    <% end %>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gyotaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBIyKkutlr2qLcjT0Z1Zgit9cYRfTwyupc"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

    <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'></script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'></script>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
        <div class="forms">
         <%= yield %>
        </div>
        <%= render "layouts/footer" %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>